metadata.format.version = "1.1"

[versions]
annotations = "24.1.0"

nexuspublish = "1.3.0"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }
